/**
 * 兜底中文词典：读不到你本机 Minecraft 语言文件时用这些
 * （全量 8500+ 条那种名靠语言文件）。
 */
export const FALLBACK_ZH: Record<string, string> = {
  // 木头 / 建材
  oak_log: "橡木原木",
  birch_log: "白桦原木",
  spruce_log: "云杉原木",
  jungle_log: "丛林原木",
  acacia_log: "金合欢原木",
  dark_oak_log: "深色橡木原木",
  oak_planks: "橡木木板",
  stick: "木棍",
  crafting_table: "工作台",
  cobblestone: "圆石",
  stone: "石头",
  dirt: "泥土",
  sand: "沙子",
  gravel: "沙砾",
  glass: "玻璃",
  torch: "火把",
  chest: "箱子",
  furnace: "熔炉",
  ladder: "梯子",
  // 矿 / 金属
  coal: "煤炭",
  charcoal: "木炭",
  raw_iron: "粗铁",
  iron_ingot: "铁锭",
  raw_copper: "粗铜",
  copper_ingot: "铜锭",
  raw_gold: "粗金",
  gold_ingot: "金锭",
  diamond: "钻石",
  emerald: "绿宝石",
  redstone: "红石",
  lapis_lazuli: "青金石",
  quartz: "下界石英",
  amethyst_shard: "紫水晶碎片",
  netherite_scrap: "下界合金碎片",
  netherite_ingot: "下界合金锭",
  ancient_debris: "远古残骸",
  iron_ore: "铁矿石",
  deepslate_iron_ore: "深层铁矿石",
  diamond_ore: "钻石矿石",
  deepslate_diamond_ore: "深层钻石矿石",
  gold_ore: "金矿石",
  coal_ore: "煤矿石",
  // 工具 / 装备
  wooden_pickaxe: "木镐",
  stone_pickaxe: "石镐",
  iron_pickaxe: "铁镐",
  diamond_pickaxe: "钻石镐",
  netherite_pickaxe: "下界合金镐",
  iron_sword: "铁剑",
  diamond_sword: "钻石剑",
  bow: "弓",
  arrow: "箭",
  shield: "盾牌",
  elytra: "鞘翅",
  bucket: "桶",
  water_bucket: "水桶",
  flint_and_steel: "打火石",
  fishing_rod: "钓鱼竿",
  // 吃的
  bread: "面包",
  wheat: "小麦",
  wheat_seeds: "小麦种子",
  apple: "苹果",
  golden_apple: "金苹果",
  carrot: "胡萝卜",
  potato: "土豆",
  cooked_beef: "熟牛肉",
  beef: "生牛肉",
  cooked_porkchop: "熟猪排",
  porkchop: "生猪排",
  chicken: "生鸡肉",
  cooked_chicken: "熟鸡肉",
};

/** 生物名（和物品同名的 id 在这里是另一回事：chicken 物品=生鸡肉，生物=鸡）。 */
export const FALLBACK_ENTITY_ZH: Record<string, string> = {
  zombie: "僵尸",
  skeleton: "骷髅",
  creeper: "苦力怕",
  spider: "蜘蛛",
  cave_spider: "洞穴蜘蛛",
  enderman: "末影人",
  slime: "史莱姆",
  witch: "女巫",
  villager: "村民",
  cow: "牛",
  pig: "猪",
  sheep: "羊",
  chicken: "鸡",
  wolf: "狼",
  iron_golem: "铁傀儡",
  drowned: "溺尸",
  husk: "尸壳",
  blaze: "烈焰人",
  ghast: "恶魂",
  piglin: "猪灵",
  hoglin: "疣猪兽",
  endermite: "末影螨",
  silverfish: "蠹虫",
};

/**
 * 口语简称 → 物品 id。
 * #value 那套、以及玩家/模型随口说的"铁""钻石"都走这里。
 */
export const ZH_ALIASES: Record<string, string> = {
  铁: "iron_ingot",
  钻石: "diamond",
  金: "gold_ingot",
  煤: "coal",
  木头: "oak_log",
  原木: "oak_log",
  木板: "oak_planks",
  石头: "cobblestone",
  圆石: "cobblestone",
  红石: "redstone",
  青金石: "lapis_lazuli",
  下界合金: "netherite_ingot",
  远古残骸: "ancient_debris",
  绿宝石: "emerald",
  羊毛: "white_wool",
  沙子: "sand",
};
